spring:
  application:
    name: yu-ai-code-mother
  # mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/yu_ai_zero_code?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456
  profiles:
    active: local
  data:
    redis:
      host: localhost
      port: 6379
      password: 123
      ttl: 3600
      username: default
  session:
    store-type: redis
    timeout: 2592000
  servlet:
    streaming:
      timeout: 0  # SSE 流式输出不超时

server:
  port: 8123
  servlet:
    context-path: /api
    session:
      cookie:
        max-age: 259200

springdoc:
  group-configs:
    - group: "Yu-ai-code-mother"
      # 扫描目录
      packages-to-scan: cn.iocoder.cloud.yuaicodemother.controller

knife4j:
  enable: true
  setting:
    language: zh_cn
